### ISSUE TITLE
Monospaced font

### ISSUE THREAD

**Issue by Abhinav-Mittal** [pzhaojohnson/rna2drawer2#27]
Hi, I have a small feature request. Can you introduce monospaced font like Courier to input structure information in dot bracket format? This will allow me to put the structure and sequence parallel to each other and do editing in the input text boxes. It's really hard to do that now.
Example:
GGGGGAAACCCCC
(((((...)))))

**Comment by pzhaojohnson** [comment]
Sounds like a good idea. Will make this change as soon as possible.

**Comment by pzhaojohnson** [comment]
Made this change in the latest update.

**Comment by Abhinav-Mittal** [comment]
Thank you! Really helpful.
